[pytest]
addopts = --headed --browser-channel=chrome

markers =
    smoke: Critical tests that verify basic application functionality
    regression: Tests that verify existing functionality
    sanity: Quick tests for specific functionality